services:
  - type: web
    name: plateforme-creche
    env: static  # ⬅ Ne surtout pas mettre "node", ici on simule une static app
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - path: /*
        static: index.html
    envVars:
      - key: VITE_API_URL
        value: https://stage-backend-c4pz.onrender.com/api/client/
      - key: VITE_STATIC_URL
        value: https://stage-backend-c4pz.onrender.com