services:
  - type: static
    name: plateforme-creche
    env: node
    repo: https://github.com/PaolaMsh/plateforme-creche
    branch: main
    buildCommand: npm run build
    installCommand: npm install
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://stage-backend-c4pz.onrender.com/api/client/
      - key: VITE_STATIC_URL
        value: https://stage-backend-c4pz.onrender.com