# render.yaml
services:
  - type: static          # on passe en static site
    name: plateforme-creche
    branch: main          # branche que Render doit surveiller
    buildCommand: npm ci && npm run build
    publishPath: dist     # dossier à servir
    env:                   # variables injectées au build time
      VITE_API_URL: https://stage-backend-c4pz.onrender.com/api/client/
      VITE_STATIC_URL: https://stage-backend-c4pz.onrender.com
