services:
  - type: web  # ← Doit absolument être 'web' et non 'static'
    name: plateforme-creche
    env: node
    runtime: node  # Nouvelle ligne cruciale
    buildCommand: npm run build
    installCommand: npm install
    staticPublishPath: ./build
    routes:
      - path: /
        headers:
          Location: /accueil
        status: 301
      - path: /accueil
        static: /build/index.html
      - path: /*
        static: /build/index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://stage-backend-c4pz.onrender.com/api/client/
      - key: VITE_STATIC_URL
        value: https://stage-backend-c4pz.onrender.com